### ISSUE TITLE
Handle Connection of an Additional Account 

### ISSUE THREAD

**Issue by peetzweg** [paritytech/useink#52]
Scenario:

1. You are connected to a dapp with 2 accounts of your wallet of choice
2. You enable inside the wallet to allow a third account to interact with the dapp.

=> As of now nothing happens for the "useWallet" hook. Is there a way to observe new accounts getting enabled in the users wallet and refresh the useWallet hook?

**Comment by DoubleOTheven** [comment]
[talisman-connect](https://www.npmjs.com/package/@talisman-connect/wallets) has a wallet subscription function. It looks like we could use that.

**Comment by DoubleOTheven** [comment]
This was solved here https://github.com/paritytech/useink/pull/56 via subscriptions
