### ISSUE TITLE
Why have hardcoded chains?

### ISSUE THREAD

**Issue by felixpolimec** [paritytech/useink#53]
What is the reason for having hardcoded chains?

Here I refer to 
https://github.com/paritytech/useink/blob/main/chains/types.ts#L17

Having this being fixed limits the ability to build dApps that are reliable on chains that are not yet launched/available or internal chains.

Happy to know the rational, or maybe I am overlooking a detail here.

**Comment by DoubleOTheven** [comment]
@felixpolimec We planned to allow for a customized chains in a near future update. Having hard coded chains makes development easier for Dapp devs, but we should allow for any

We are looking using [talisman chaindata](https://github.com/TalismanSociety/chaindata), which has a ton of chains implemented already.
